name: Build Flet Android AAB
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Flet and Dependencies
        run: |
          pip install flet

      - name: Setup Flutter Workflow
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'

      - name: Build Android App Bundle (.aab)
        run: |
          flet build aab

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-bundle
          path: build/outputs/bundle/release/app-release.aab
